version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=root-db
    ports:
      - '27017:27017'
    
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - dbdata6:/data/db

volumes:
  dbdata6: